export const ON_ENVIAR_MENSAGEM_ERROR = 'ON_ENVIAR_MENSAGEM';
export const ON_LIMPAR_MENSAGEM_ERROR = 'ON_LIMPAR_MENSAGEM_ERROR';
export const ON_ADICIONAR_MENSAGEM_RECEBIDA = 'ON_ADICIONAR_MENSAGEM_RECEBIDA';

export const ON_INICIAR_SERVIDOR = 'ON_INICIAR_SERVIDOR';
export const ON_FECHAR_SERVIDOR = 'ON_FECHAR_SERVIDOR';
export const ON_CONECTAR_CLIENTE = 'ON_CONECTAR_CLIENTE';
export const ON_FECHAR_CLIENTE = 'ON_FECHAR_CLIENTE';
